"""dish owner + shop/dish audit fields (reviewed_by/reviewed_at/reject_reason)

Revision ID: 2fd47094a941
Revises: e0a5360d786b
Create Date: 2026-09-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2fd47094a941'
down_revision = 'e0a5360d786b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reject_reason', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_shops_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])

    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reject_reason', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_dishes_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dishes_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])

    # 回填：历史菜品归属其店铺创建者（管理员/商户创建的种子菜 owner 保持 NULL）
    op.execute(
        "UPDATE dishes d INNER JOIN shops s ON d.shop_id = s.id "
        "SET d.owner_id = s.owner_id WHERE s.owner_id IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_dishes_reviewed_by'))
        batch_op.drop_index(batch_op.f('ix_dishes_owner_id'))
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shops_reviewed_by'))
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###
