"""add view_history

Revision ID: 701f22793f98
Revises: 2fd47094a941
Create Date: 2026-09-09 11:10:24.392315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701f22793f98'
down_revision = '2fd47094a941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_view_user_target')
    )
    with op.batch_alter_table('view_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_view_history_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_view_user_viewed', ['user_id', 'viewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_history', schema=None) as batch_op:
        batch_op.drop_index('ix_view_user_viewed')
        batch_op.drop_index(batch_op.f('ix_view_history_user_id'))

    op.drop_table('view_history')
    # ### end Alembic commands ###
