"""add circles and membership; extend messages for group dm school chat

Revision ID: 83a882ee4ddd
Revises: cf51b12b97a2
Create Date: 2026-09-03 09:14:16.464352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a882ee4ddd'
down_revision = 'cf51b12b97a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circles_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circles_school_id'), ['school_id'], unique=False)

    op.create_table('circle_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'circle_id', name='uq_circle_member_user_circle')
    )
    with op.batch_alter_table('circle_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circle_memberships_circle_id'), ['circle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circle_memberships_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('circle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_circle_id'), ['circle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_school_id'), ['school_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['id'])
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'])
        batch_op.create_foreign_key(None, 'circles', ['circle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_school_id'))
        batch_op.drop_index(batch_op.f('ix_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_messages_circle_id'))
        batch_op.drop_column('read_at')
        batch_op.drop_column('school_id')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('circle_id')
        batch_op.drop_column('images')

    with op.batch_alter_table('circle_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circle_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_circle_memberships_circle_id'))

    op.drop_table('circle_memberships')
    with op.batch_alter_table('circles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circles_school_id'))
        batch_op.drop_index(batch_op.f('ix_circles_creator_id'))

    op.drop_table('circles')
    # ### end Alembic commands ###
