"""add event_logs

Revision ID: 975e70c5b52e
Revises: e2c8a4d6b1f3
Create Date: 2026-09-10 09:23:27.200358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975e70c5b52e'
down_revision = 'e2c8a4d6b1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_event_logs_school_id'))
        batch_op.drop_index(batch_op.f('ix_event_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_event_logs_actor_id'))

    op.drop_table('event_logs')
    # ### end Alembic commands ###
