"""drop school description; keep address

Revision ID: aa6dc073e1a4
Revises: 9a7eb38e5578
Create Date: 2026-09-02 08:43:29.998523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa6dc073e1a4'
down_revision = '9a7eb38e5578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))

    # ### end Alembic commands ###
