"""merchant role: shop owner/status, dish status, post shop required

Revision ID: cf51b12b97a2
Revises: caeb7ab3fc4e
Create Date: 2026-09-02 09:59:57.595710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf51b12b97a2'
down_revision = 'caeb7ab3fc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='approved', nullable=False))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='approved', nullable=False))
        batch_op.create_index(batch_op.f('ix_shops_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shops_owner_id'))
        batch_op.drop_column('status')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
