"""add messages.shop_id for shop annotation

Revision ID: e0a5360d786b
Revises: 83a882ee4ddd
Create Date: 2026-09-07 09:56:50.348518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a5360d786b'
down_revision = '83a882ee4ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_shop_id'), ['shop_id'], unique=False)
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_shop_id'))
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
